###
POST http://localhost:5000/api/reg
Content-Type: application/json

{
    "name":"lokesh",
    "email":"mots2@gmail.com",
    "password":"123",
    "repassword":"123"
}
###
POST http://localhost:5000/api/logincheck
Content-Type: application/json

{
    "email":"lokesh@gmail.com",
    "password":"1233"
}